//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveMgr.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpMgr.Resources.Common.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMICS.
        /// </summary>
        public static string Academics {
            get {
                return ResourceManager.GetString("Academics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP ROLE AND ACTION.
        /// </summary>
        public static string ActionRoleMap {
            get {
                return ResourceManager.GetString("ActionRoleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddBooks.
        /// </summary>
        public static string AddBooks {
            get {
                return ResourceManager.GetString("AddBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDENT.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL FEES ENTRY.
        /// </summary>
        public static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAFF.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN CONTROL.
        /// </summary>
        public static string AdminControl {
            get {
                return ResourceManager.GetString("AdminControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal.
        /// </summary>
        public static string Appraisal {
            get {
                return ResourceManager.GetString("Appraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE.
        /// </summary>
        public static string ApproveDues {
            get {
                return ResourceManager.GetString("ApproveDues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Action.
        /// </summary>
        public static string EntitlementAction {
            get {
                return ResourceManager.GetString("EntitlementAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKS ENTRY.
        /// </summary>
        public static string MarksEntry {
            get {
                return ResourceManager.GetString("MarksEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASTER INFORMATION.
        /// </summary>
        public static string MasterInformation {
            get {
                return ResourceManager.GetString("MasterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transactions.
        /// </summary>
        public static string MyTransactions {
            get {
                return ResourceManager.GetString("MyTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEES COLLECTION ENTRY.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINCIPAL PANEL.
        /// </summary>
        public static string PrincipalPanel {
            get {
                return ResourceManager.GetString("PrincipalPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMOTE STUDENTS.
        /// </summary>
        public static string PromoteStudents {
            get {
                return ResourceManager.GetString("PromoteStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PROMOTION.
        /// </summary>
        public static string PromotionBatch {
            get {
                return ResourceManager.GetString("PromotionBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER REMARKS.
        /// </summary>
        public static string RemarksEntry {
            get {
                return ResourceManager.GetString("RemarksEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULES CREATION.
        /// </summary>
        public static string RulesCreation {
            get {
                return ResourceManager.GetString("RulesCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Appraisee.
        /// </summary>
        public static string SearchAppraisee {
            get {
                return ResourceManager.GetString("SearchAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT HISTORY.
        /// </summary>
        public static string SearchTransaction {
            get {
                return ResourceManager.GetString("SearchTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAFF.
        /// </summary>
        public static string SearchUser {
            get {
                return ResourceManager.GetString("SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Evaluation.
        /// </summary>
        public static string SelfAppraisal {
            get {
                return ResourceManager.GetString("SelfAppraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDENT.
        /// </summary>
        public static string StudentSearch {
            get {
                return ResourceManager.GetString("StudentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTION ENTRY.
        /// </summary>
        public static string TransactionEntry {
            get {
                return ResourceManager.GetString("TransactionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULES FOR FEES STYLE.
        /// </summary>
        public static string TransactionMaster {
            get {
                return ResourceManager.GetString("TransactionMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transaction Rule.
        /// </summary>
        public static string TransactionRuleAdd {
            get {
                return ResourceManager.GetString("TransactionRuleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULES FOR FEES STRUCTURE.
        /// </summary>
        public static string TransactionRuleSearch {
            get {
                return ResourceManager.GetString("TransactionRuleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD DATA FROM EXCEL.
        /// </summary>
        public static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER CREATION.
        /// </summary>
        public static string UserCreation {
            get {
                return ResourceManager.GetString("UserCreation", resourceCulture);
            }
        }
    }
}
